version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=share_it
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/share_it
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: db
    depends_on:
      - db
    networks:
      - app-network

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      SHAREIT_SERVER_URL: http://server:9090/
    depends_on:
      - server
    networks:
      - app-network
networks:
  app-network:

volumes:
  pgdata: